<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions 
 * @package    Communityad
 * @copyright  Copyright 2009-2011 BigStep Technologies Pvt. Ltd.
 * @license    http://www.socialengineaddons.com/license/
 * @version    $Id: faq.tpl 2011-02-16 9:40:21Z SocialEngineAddOns $
 * @author     SocialEngineAddOns
 */
?>

<h2><?php echo $this->translate("Community Ads Plugin") ?></h2>

<?php if( count($this->navigation) ): ?>
	<div class='communityad_admin_tabs'>
		<?php	echo $this->navigation()->menu()->setContainer($this->navigation)->render() ?>
	</div>
<?php endif; ?>

<script type="text/javascript">
  function guideline_show(id) {
    if($(id).style.display == 'block') {
      $(id).style.display = 'none';
    } else {
      $(id).style.display = 'block';
    }
  }
</script>

<style type="text/css">
.communityad_guidelines_faq li > div{
	clear:both;
	border-left:3px solid #ccc;
	padding:5px 5px 5px 10px;
	margin:5px;
	font-family:arial;
	line:height:18px;
}
.communityad_guidelines_faq li div b{font-weight:bold;}
.communityad_guidelines_faq li div p{clear:both;margin:5px 0;}
.code{ background-color:#F9F6D5;padding:10px;color:#000;font-family: "Trebuchet MS",tahoma,verdana,arial,serif;}
</style>

	<?php echo $this->htmlLink(array('route' => 'admin_default', 'module' => 'communityad', 'controller' => 'widgets', 'action' => 'manage'), $this->translate("Back to Manage Ad Blocks"), array('class'=>'cmad_icon_back buttonlink')) ?>
	<br style="clear:both;" /><br />

<div class='clear'>
<div class='settings'>
<h3><?php echo $this->translate("Guidelines for placing Ad Blocks on some Popular Non-widgetized Pages") ?></h3>
<p><?php echo $this->translate('With this plugin, you can also place Ad Blocks on the Non-Widgetized pages of your site. These are the pages which are not available for layout customization in the Layout Editor of SocialEngine Admin Panel. To place Ad Blocks on such pages, firstly create a new Ad Block for Non-Widgetized Page from the "Manage Ad Blocks" section. Then go to Manage Ad Blocks page to view the code for this Ad Block. Copy the code of the Ad Block and paste it at the desired location in the template file of the non-widgetized page to display advertisements over there. Please be sure that you paste the code at the right place. After pasting the code in your template page, if the page layout becomes disorganized, then contact your theme developer to assist you.<br />Below are the guidelines for placing Ad blocks on some popular Non-Widgetized pages. Use the code generated for Ad Blocks on these pages from the "Manage Ad Blocks" section.') ?></p><br />

<div class="admin_files_wrapper" style="width:930px;">
	<ul class="admin_files communityad_guidelines_faq" style="max-height:none;">
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_1');"><?php echo $this->translate("Login Page");?></a>
			<div class='faq' style='display: none;' id='guideline_1'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/auth/login.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Login page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;?php echo $this->form->render($this)   ?&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />
&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>

		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_2');"><?php echo $this->translate("Signup Page");?></a>
			<div class='faq' style='display: none;' id='guideline_2'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/signup/index.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Signup page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;?php echo $this-></div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_3');"><?php echo $this->translate("Video view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_3'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Video/views/scripts/index/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Video view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;div class="video_view video_view_container"&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>

		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_4');"><?php echo $this->translate("Video browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_4'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Video/views/scripts/index/browse.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Video browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;<br />&lt;div class=\'layout_middle\'&gt;</div><p><br />2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>

		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_5');"><?php echo $this->translate("Video manage Page");?></a>
			<div class='faq' style='display: none;' id='guideline_5'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Video/views/scripts/index/manage.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Video manage page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt; &lt;div class=\'layout_middle\'&gt;</div><p><br />2. Now, insert the below ad block code, that was generated, just after the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>

		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_6');"><?php echo $this->translate("Group browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_6'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Group/views/scripts/index/browse.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Group browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>

		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_7');"><?php echo $this->translate("Group manage Page");?></a>
			<div class='faq' style='display: none;' id='guideline_7'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Group/views/scripts/index/manage.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Group manage page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;<br /><br />&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>

		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_8');"><?php echo $this->translate("Music browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_8'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Music/views/scripts/index/browse.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Music browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><p><br />2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>

		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_9');"><?php echo $this->translate("Music manage Page");?></a>
			<div class='faq' style='display: none;' id='guideline_9'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Music/views/scripts/index/manage.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Music manage page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    	<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_10');"><?php echo $this->translate("Music view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_10'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Music/views/scripts/playlist/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Music view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;h2&gt; &lt;?php echo $playlist->getTitle() ?&gt; &lt;/h2&gt;</div><p><br />2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    	<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_11');"><?php echo $this->translate("Document view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_11'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Document/views/scripts/index/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Document view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    	<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_12');"><?php echo $this->translate("Classfied browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_12'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Classified/views/scripts/index/index.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Classfied browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    	<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_13');"><?php echo $this->translate("Classfied view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_13'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Classified/views/scripts/index/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Classfied view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    	<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_14');"><?php echo $this->translate("Poll browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_14'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Poll/views/scripts/index/browse.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Poll browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><p><br />2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    	<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_15');"><?php echo $this->translate("Poll view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_15'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Poll/views/scripts/poll/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Poll view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;div class=\'polls_view\'&gt; style="margin-top:10px"</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    	<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_16');"><?php echo $this->translate("Album browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_16'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Album/views/scripts/index/browse.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Album browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
    <li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_17');"><?php echo $this->translate("Album photo view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_17'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Album/views/scripts/photo/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Album photo view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;div class="layout_middle"&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_18');"><?php echo $this->translate("Event browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_18'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Event/views/scripts/index/browse.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Event browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_19');"><?php echo $this->translate("Blog browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_19'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Blog/views/scripts/index/index.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Blog browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;/div&gt;&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div style="margin-top:15px;"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_20');"><?php echo $this->translate("Blog view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_20'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Blog/views/scripts/index/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Blog view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_21');"><?php echo $this->translate("Forum browse Page");?></a>
			<div class='faq' style='display: none;' id='guideline_21'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Forum/views/scripts/index/index.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Forum browse page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;ul class="forum_categories"&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_22');"><?php echo $this->translate("Forum topic view Page");?></a>
			<div class='faq' style='display: none;' id='guideline_22'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Forum/views/scripts/topic/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Forum topic view page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;div class="forum_topic_title_wrapper"&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_23');"><?php echo $this->translate("Contact us Page");?></a>
			<div class='faq' style='display: none;' id='guideline_23'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Core/views/scripts/help/contact.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Contact us page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;?php if( $this->status ): ?&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_24');"><?php echo $this->translate("Terms of Service Page");?></a>
			<div class='faq' style='display: none;' id='guideline_24'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Core/views/scripts/help/terms.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Terms of Service page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;h2&gt;&lt;?php echo $this->translate(\'Terms of Service\') ?&gt;&lt;/h2&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just after the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_25');"><?php echo $this->translate("Privacy Page");?></a>
			<div class='faq' style='display: none;' id='guideline_25'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Core/views/scripts/help/privacy.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Privacy page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;h2&gt;&lt;?php echo $this->translate(\'Privacy Statement\') ?&gt;&lt;/h2&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just after the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
				</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_26');"><?php echo $this->translate("Invite Page");?></a>
			<div class='faq' style='display: none;' id='guideline_26'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Invite/views/scripts/index/index.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Invite page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the line given below:</p><div class="code">&lt;div id="invite_form"&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned line.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_27');"><?php echo $this->translate("Message Inbox page");?></a>
			<div class='faq' style='display: none;' id='guideline_27'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Messages/views/scripts/messages/inbox.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Message Inbox page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;?php if( $this->paginator->getTotalItemCount() <= 0 ): ?&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_28');"><?php echo $this->translate("Sent Messages Page");?></a>
			<div class='faq' style='display: none;' id='guideline_28'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Messages/views/scripts/messages/outbox.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Sent Messages page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;?php if( count($this->paginator) ): ?&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_29');"><?php echo $this->translate("Compose Message Page");?></a>
			<div class='faq' style='display: none;' id='guideline_29'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Messages/views/scripts/messages/compose.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Compose Message page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;?php echo $this->form->render($this) ?&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_30');"><?php echo $this->translate("Message View Page");?></a>
			<div class='faq' style='display: none;' id='guideline_30'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/Messages/views/scripts/messages/view.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Message View page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;div class="tabs"&gt;<br />&lt;?php<br />// Render the menu<br />echo $this->navigation()<br />->menu()<br />->setContainer($this->navigation)<br />->render();<br />?&gt;<br />&lt;/div&gt;<br />&lt;/div&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just after the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_31');"><?php echo $this->translate("General Settings Page");?></a>
			<div class='faq' style='display: none;' id='guideline_31'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/settings/general.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of General Settings page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;div class="tabs"&gt;<br />&lt;?php<br />// Render the menu<br />echo $this->navigation()<br />->menu()<br />->setContainer($this->navigation)<br />->render();<br />?&gt;<br />&lt;/div&gt;<br />&lt;/div&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just after the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_32');"><?php echo $this->translate("Privacy Settings Page");?></a>
			<div class='faq' style='display: none;' id='guideline_32'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/settings/privacy.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Privacy Settings page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;div class="tabs"&gt;<br />&lt;?php<br />// Render the menu<br />echo $this->navigation()<br />->menu()<br />->setContainer($this->navigation)<br />->render();<br />?&gt;<br />&lt;/div&gt;<br />&lt;/div&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just after the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_33');"><?php echo $this->translate("Notification Settings Page");?></a>
			<div class='faq' style='display: none;' id='guideline_33'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/settings/notifications.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Notification Settings page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;?php echo $this->form->render($this) ?&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_34');"><?php echo $this->translate("Network Settings Page");?></a>
			<div class='faq' style='display: none;' id='guideline_34'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/settings/network.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Network Settings page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;div class=\'layout_middle\'&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_35');"><?php echo $this->translate("Change Password Page");?></a>
			<div class='faq' style='display: none;' id='guideline_35'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/settings/password.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Change Password page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;?php echo $this->form->render($this) ?&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just before the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		<li>
			<a href="javascript:void(0);" onClick="guideline_show('guideline_36');"><?php echo $this->translate("Delete Account Page");?></a>
			<div class='faq' style='display: none;' id='guideline_36'>
				<?php echo $this->translate('<b>For this page, place the Ad Block code in the template file: '). $this->translate('"/application/modules/User/views/scripts/settings/delete.tpl"</b><p>Example: In this example, we show how to place an ordinary ad block (non-featured, non-sponsored) in the right side of Delete Account page. First, create an Ad Block from the Manage Ad Blocks page for a "Non-Widgetized Page", and "Non-Widgetized Page: Right Column Ads" block position. Then, copy the code for this ad block from the Manage Ad Blocks page. Now:</p><br /><p>1. Open the template file and search for the code given below:</p><div class="code">&lt;div class="tabs"&gt;<br />&lt;?php<br />// Render the menu<br />echo $this->navigation()<br />->menu()<br />->setContainer($this->navigation)<br />->render();<br />?&gt;<br />&lt;/div&gt;<br />&lt;/div&gt;</div><br /><p>2. Now, insert the below ad block code, that was generated, just after the above mentioned code.</p><p><b>Code</b></p><div class="code">&lt;div class="layout_right"&gt;<br />&lt;?php echo $this->content()->renderWidget("communityad.right-none"); ?&gt;<br />&lt;/div&gt;<br />&lt;div class="layout_middle"&gt;</div><br /><p>3. Now, insert the below line of code at the end of this file.</p><div class="code">&lt;/div&gt;</div><br />'). $this->translate('<p>For placing an ad block at a different position on this page, generate the corresponding ad block code for it by selecting the desired Ad Block Widget for Non-Widgetized Page in "Manage Ad Blocks", and place it at the appropriate location in the template file.</p>');?>
			</div>
		</li>
		
		</ul>
	</div>
</div>
</div>