<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Sitepage
 * @copyright  Copyright 2010-2011 BigStep Technologies Pvt. Ltd.
 * @license    http://www.socialengineaddons.com/license/
 * @version    $Id: chnagelog.php.tpl 2011-05-05 9:40:21Z SocialEngineAddOns $
 * @author     SocialEngineAddOns
 */

return array(
  '4.1.7p2' => array(
		'Api/Core.php' => 'Minor optimizations ',
		'Api/Layoutcore.php' => 'Minor modifications for Activity Feed',
		'Api/SubCore.php' => 'Minor optimizations',
		'Api/Suggestion.php' => 'Minor modifications Suggestions / Recommendations Plugin',
		'controllers/AlbumController.php' => 'Minor modifications for Activity Feed and Suggestions / Recommendations Plugin',
		'controllers/AdminController.php' => 'Minor modifications for 3rd Level Categories and Suggestions / Recommendations Plugin',
		'controllers/AdminDefaultlayoutController.php' => 'Minor modifications for Activity Feed',
		'controllers/AdminExtensionController.php' => 'Added method for extensions list',
		'controllers/AdminImportlistingController.php' => 'Fixed issue with rollback the pages in Page importing',
		'controllers/AdminItemsController.php' => 'Minor modifications',
		'controllers/AdminLayoutController.php' => 'Minor modifications',
		'controllers/AdminSettingsController.php' => 'Minor modifications',
		'controllers/AdminviewpagewidgetController.php' => 'Minor modifications for Activity Feed',
		'controllers/AdminViewsitepageController.php' => 'Minor modifications for 3rd Level Categories',
		'controllers/IndexController.php' => 'Minor modifications for 3rd Level Categories and page based network',
		'controllers/LayoutController.php' => 'Minor modifications for 3rd Level Categories and Activity Feed',
		'controllers/PhotoController.php' => 'Minor modifications for Activity Feed; Fixed Log Errors',
		'controllers/ProfileController.php' => 'Fixed Log Errors and Print Page Profile,Minor modifications for 3rd Level Categories',
		'controllers/TopicController.php' => 'Minor modifications for Activity Feed;Added dashboard link on Create Pages',
		'externals/images/likebox.png' => 'Changed',
		'externals/images/gray_arrow.png' => 'Added',
		'externals/images/options.png' => 'Added',
		'externals/scripts/core.js' => 'Minor modifications for 3rd Level Categories',
		'externals/styles/admin/main.css' => 'Added styles',
		'externals/styles/main.css' => 'CSS Optimizations',
		'externals/styles/style_sitepage.css' => 'Added styles and CSS Optimizations for featured pages widget',
		'externals/styles/style_sitepage_dashboard.css ' => 'CSS Optimizations',
		'externals/styles/style_sitepage_profile.css' => 'Fixed issue Of Print Page Profile;Added styles',
		'externals/styles/sitepage -tooltip.css' => 'Added styles; CSS Optimizations',
		'Form/Admin/Changecategory.php' => 'Minor modifications for 3rd Level Categories',
		'Form/Admin/Global.php' => 'Minor modifications',
		'Form/Admin/Settings/ActivityFeed.php' => 'Added',
		'Form/Admin/Settings/Level.php' => 'Minor modifications',
		'Form/AdminLayout/LayoutBlock.php' => 'Minor modifications for Activity Feed;',
		'Form/Create.php' => ' Added network based privacy,Minor modifications for 3rd Level Categories',
		'Form/Managesearch.php' => 'New options "Most Reviewed and Hightest Rated" added in "Browse by" field;Minor modifications for 3rd Level Categories',
		'Form/Photo/Album.php' => 'Minor modifications for Activity Feed',
		'Form/Search.php' => 'New options "Most Reviewed and Hightest Rated" added in "Browse by" field;Added network based privacy;Added a new field "Only Pages with Reviews",Minor modifications for 3rd Level Categories',
		'Model/DbTable/Categories.php' => 'Minor modifications',
		'Model/DbTable/Content.php' => 'Minor modifications for Activity Feed',
		'Model/DbTable/Albums.php' => 'Minor modifications for Activity Feed',
		'Model/DbTable/Itemofthedays.php' => 'Minor modifications',
		'Model/DbTable/Pages.php' => 'Minor modifications',
		'Model/DbTable/Pagestatistics.php' => 'Minor modifications',
		'Plugin/Core.php' => 'Minor modifications for Activity Feed',
		'Plugin/Menus.php' => 'Fixed issue Of Print Page Profile',
		'settings/content.php' => 'Minor modifications',
		'settings/install.php' => 'Minor modification for Suggestions / Recommendations Plugin',
		'settings/manifest.php' => 'Incremented version',
		'settings/my.sql' => 'Incremented version',
		'settings/my-upgrade-4.1.7-4.1.7p2.sql' => 'Added',
		'views/scripts/_formSubcategory.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/_recently_popular_random_page.tpl' => 'Minor modifications',
		'views/scripts/_Subcategory.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/partial_views.tpl' => 'Show numbers of reviews',
		'views/scripts/admin/change -category.tpl' => 'Added',
		'views/scripts/admin/changecategory.tpl' => 'Remove',
		'views/scripts/admin-defaultlayout/index.tpl' => 'Minor modifications for Activity Feed',
		'views/scripts/admin-extension/index.tpl' => 'Minor modifications',
		'views/scripts/admin-extension/information.tpl' => 'Minor modifications',
		'views/scripts/admin-extension/upgrade.tpl' => 'Minor modifications',
		'views/scripts/admin-importlisting/rollback.tpl' => 'Minor modifications',
		'views/scripts/admin-layout/layout.tpl' => 'Minor modifications for Activity Feed',
		'views/scripts/admin-settings/activity -feed' => 'Added',
		'views/scripts/admin-settings/activity -feed.tpl' => 'Added',
		'views/scripts/admin-settings/faq_help.tpl' => 'Minor modifications for Activity Feed',
		'views/scripts/admin-settings/form -search.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/admin-settings/index.tpl' => 'Minor modifications for Activity Feed and Page based network',
		'views/scripts/admin-settings/overwrite.tpl' => 'Added',
		'views/scripts/admin-settings/overwrite -activity -widgets.tpl' => 'Added',
		'views/scripts/admin-settings/sitepagecategories.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/admin-viewsitepage/detail.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/admin-viewsitepage/index.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/album/compose -upload.tpl' => 'Minor modifications for Activity Feed',
		'views/scripts/index/create.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/index/edit.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/index/manage.tpl' => 'Minor modifications for 3rd Level Categories',
		'views/scripts/layout/layout.tpl' => 'Minor modifications for Activity Feed',
		'views/scripts/like/mylikes.tpl' => 'Show numbers of reviews',
		'views/scripts/photo/upload -album.tpl' => 'Added dashboard link on Create Pages',
		'views/scripts/profile/print.tpl' => 'Fixed issue Of Print Page Profile',
		'views/scripts/topic/create.tpl' => 'Added dashboard link on Create Pages',
		'widgets/alphabeticsearch-sitepage/Controller.php' => 'Fixed Url Issue',
		'widgets/alphabeticsearch-sitepage/index.tpl' => 'Fixed Url Issue',
		'widgets/category-pages-sitepage ' => 'Added',
		'widgets/categories-sitepage/Controller.php' => 'Minor modifications for 3rd Level Categories',
		'widgets/categories-sitepage/index.tpl' => 'Minor modifications for 3rd Level Categories',
		'widgets/categories/Controller.php' => 'Minor modifications for 3rd Level Categories',
		'widgets/categories/index.tpl' => 'Minor modifications for 3rd Level Categories',
		'widgets/categories/Controller.php' => 'Some New Settings for Category Widget',
		'widgets/discussion-sitepage/index.tpl' => 'Minor modifications for Activity Feed',
		'widgets/extension-show' => 'Added',
		'widgets/info-sitepage/Controller.php' => 'Minor modifications for 3rd Level Categories',
		'widgets/info-sitepage/index.tpl' => 'Minor modifications for 3rd Level Categories',
		'widgets/information-sitepage/Controller.php' => 'Minor modifications for 3rd Level Categories',
		'widgets/information-sitepage/index.tpl' => 'Minor modifications for 3rd Level Categories',
		'widgets/item-sitepage/Controller.php' => 'Minor modifications',
		'widgets/location-sitepage/index.tpl' => 'Minor modifications for Activity Feed',
		'widgets/overview-sitepage/index.tpl' => 'Minor modifications for Activity Feed',
		'widgets/pages-sitepage/Controller.php' => 'Minor modifications for 3rd Level Categories',
		'widgets/pages-sitepage/index.tpl' => 'Minor modifications of reviews in widgets',
		'widgets/photos-sitepage/index.tpl' => 'Minor modifications for Activity Feed',
		'widgets/profile-sitepage/index.tpl' => 'Minor modifications of reviews in widgets',
		'widgets/search-sitepage/Controller.php' => 'Minor modifications for 3rd Level Categories',
		'widgets/search-sitepage/index.tpl' => 'Minor modifications for 3rd Level Categories',
		'widgets/slideshow-sitepage/index.tpl' => 'Minor modifications of reviews in widgets',
		'widgets/suggestedpage-sitepage/index.tpl' => 'Minor modifications of reviews in widgets',
		'widgets/widgetlinks-sitepage/Controller.php' => 'Minor modifications for Activity Feed',

	),

  '4.1.7p1' => array(
		'Api/Core.php' => 'Minor optimizations, Fixed Issue',
		'controllers/AdminLayoutController.php' => 'Fixed Issue',
		'controllers/AdminPackageController.php' => 'Fixed Issue',
		'controllers/license/widgetSettings.php' => 'Fixed Issue',
		'controllers/DashboardController.php' => 'Fixed Issue',
		'controllers/AdminImportlistingController.php' => 'Fixed the  issue of import pages from csv file',
		'externals/styles/style_sitepage.css' => 'Fixed Issue',
		'settings/install.php' => 'Fixed Issue',
		'settings/content.php' => 'Fixed Issue',
		'settings/my.sql' => 'Fixed Issue, Incremented version',
		'settings/manifest.php' => 'Fixed Issue, Incremented version',
		'Form/Admin/Adsettings.php' => 'Fixed Issue',
		'Form/Admin/Package/Create.php' => 'Fixed Issue',
		'Model/DbTable/Pages.php' => 'Fixed Issue',
		'Plugin/Core.php' => 'Fixed Issue',
		'views/scripts/partial_views.tpl' => 'Fixed the issue of rating  stars at manage page',
		'views/scripts/edit_tabs.tpl' => 'Change the order of tabs on Edit dashboard Page',
		'views/scripts/index/manage.tpl' => 'My like work at manage page tab',
		'views/scripts/admin-layout/layout.tpl' => 'Fixed Issue',
		'views/scripts/admin-layout/widget.tpl' => 'Fixed Issue',
		'views/scripts/admin-settings/adsettings.tpl' => 'Fixed Issue',
		'views/scripts/dashboard/upload-photo.tpl' => 'Fixed Issue',
		'views/scripts/index/create.tpl' => 'Fixed Issue',
		'views/scripts/photo/make-page-profile-photo.tpl' => 'Fixed Issue',
		'widgets/alphabeticsearch-sitepage/Controller.php' => 'Fixed Issue',
		'widgets/alphabeticsearch-sitepage/index.tpl' => 'Fixed Issue',
		'widgets/location-sitepage/index.tpl' => 'Fixed Issue',
		'widgets/overview-sitepage/index.tpl' => 'Fixed Issue',
		'widgets/pages-sitepage/index.tpl' => 'Fixed Issue',
		'widgets/searchbox-sitepage/index.tpl' => 'Fixed Issue',
		'widgets/slideshow-sitepage/index.tpl' => 'Minor optimizations',
	),

  '4.1.7' => array(
		'views/scripts/admin-package/index.tpl - Fixed Issue',
		'Api/SubCore.php - Adding, delete create activity feed of extensions',
		'Model/Photo.php - Fixed Issue',
		'Form/Album/Edit.php' => 'Minor optimizations',
		'Form/Photo/Album.php  - Minor optimizations',
		'views/scripts/admin-settings/adsettings.tpl  - Minor optimizations',
		'views/scripts/make-page-profile-photo.tpl  - Minor optimizations',
		'Api/Core.php - Fixed Issue',
		'Form/Admin/Global.php - Fixed Issue',
		'Form/Search.phpcontrollers/AdminSettingsController.php - Fixed Issue',
		'controllers/PhotoController.php - Fixed Issue',
		'settings/content.php - Fixed Issue',
		'settings/manifest.php - Fixed Issue',
		'views/scripts/photo/view.tpl - Fixed Issue',
		'widgets/albums-sitepage/Controller.php - Fixed Issue',
		'widgets/mostrecentphotos-sitepage/Controller.php - Fixed Issue',
		'widgets/photocomment-sitepage/Controller.php - Fixed Issue',
		'widgets/photolike-sitepage/Controller.php - Fixed Issue',
		'widgets/photorecent-sitepage/Controller.php - Fixed Issue',
		'widgets/photos-sitepage/Controller.php - Fixed Issue',
		'widgets/popularphotos-sitepage/Controller.php - Fixed Issue',
		'settings/my-upgrade-4.1.6p3-4.1.7.sql - Added',
		'views/scripts/photo/make-page-profile-photo.tpl - Added',
		'widgets/alphabeticsearch-sitepage - Added',
		'widgets/alphabeticsearch-sitepage/Controller.php - Added',
		'widgets/alphabeticsearch-sitepage/index.tpl - Added',
		'Model/DbTable/Claims.php  - Minor optimizations',
		'controllers/IndexController.php  - Minor optimizations',
		'controllers/AdminClaimController.php  - Minor optimizations',
		'controllers/AdminController.php  - Minor optimizations',
		'controllers/AdminImportlistingController.php  - Minor optimizations',
		'controllers/InsightsController.php  - Minor optimizations',
		'widgets/pages-sitepage/Controller.php  - Minor optimizations',
		'views/scripts/_recently_popular_random_page.tpl  - Minor optimizations',
		'widgets/recently-popular-random-sitepage/index.tpl  - Minor optimizations',
  ),
)
?>
