<?php
/**
 * SocialEngine
 *
 * @category   Application_Core
 * @package    Fields
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.com/license/
 * @version    $Id: fields.php 9747 2012-07-26 02:08:08Z john $
 * @author     John
 */
return array(
/*
Nickname
-First Name
-Last Name
-Gender
-Birthday
-About Me
-Websites
-Twitter
-Facebook
-AIM

-Country
-City
-ZIP/Postal Code
Height
-Weight
-Income
-Occupation
-Religion
-Education
-Relationship Status
-Ethnicity
-Interests
Hobbies
Favorite Music
Favorite Movies
Favorite Books

Currency
Primary Sport
*/
  'categories' => array(
    'generic' => array(
      'label' => 'Generic',
    ),
    'specific' => array(
      'label' => 'Specific',
    ),
  ),
  'dependents' => array(
    'select',
    'multiselect',
    'multi_checkbox',
    'radio',
    'gender',
    'profile_type',
  ),
  'fields' => array(
    // Generic
    'text' => array(
      'label' => 'Single-line Text Input',
      'category' => 'generic',
      'helper' => 'fieldText',
      'multi' => false,
      'dependents' => false,
    ),
    'textarea' => array(
      'label' => 'Multi-line Text Input',
      'category' => 'generic',
      'helper' => 'fieldTextarea',
      'multi' => false,
      'dependents' => false,
    ),
    'select' => array(
      'label' => 'Select Box',
      'category' => 'generic',
      'helper' => 'fieldSelect',
      'multi' => false,
      'dependents' => true,
    ),
    'radio' => array(
      'label' => 'Radio Buttons',
      'category' => 'generic',
      'helper' => 'fieldSelect',
      'multi' => false,
      'dependents' => true,
    ),
    'checkbox' => array(
      'label' => 'Single Checkbox',
      'category' => 'generic',
      'helper' => 'fieldSelect',
      'multi' => false,
      'dependents' => true,
    ),
    'multiselect' => array(
      'label' => 'Multi Select Box',
      'category' => 'generic',
      'helper' => 'fieldMultiselect',
      'multi' => true,
      'dependents' => true,
    ),
    'multi_checkbox' => array(
      'label' => 'Multi Checkbox',
      'category' => 'generic',
      'helper' => 'fieldMultiselect',
      'multi' => true,
      'dependents' => true,
    ),
    'integer' => array(
      'label' => 'Integer',
      'category' => 'generic',
      'helper' => 'fieldText',
      'multi' => false,
      'dependents' => false,
    ),
    'float' => array(
      'label' => 'Float',
      'category' => 'generic',
      'helper' => 'fieldText',
      'multi' => false,
      'dependents' => false,
    ),
    'date' => array(
      'label' => 'Date',
      'category' => 'generic',
      'helper' => 'fieldDate',
      'multi' => false,
      'dependents' => false,
    ),
    'heading' => array(
      'label' => 'Heading',
      'category' => 'generic',
      'helper' => 'fieldHeading',
      'multi' => false,
      'dependents' => false,
    ),
    // Specific
    'profile_type' => array(
      'base' => 'select',
      'label' => 'Profile Type',
      'category' => false, // Hide this
    ),
    'first_name' => array(
      'base' => 'text',
      'label' => 'First Name',
      'category' => 'specific',
    ),
    'last_name' => array(
      'base' => 'text',
      'label' => 'Last Name',
      'category' => 'specific',
    ),
    'gender' => array(
      'base' => 'select',
      'label' => 'Gender',
      'category' => 'specific',
      'importOptions' => true,
      'multiOptions' => array(
        'Male',
        'Female',
      )
    ),

    'birthdate' => array(
      'base' => 'date',
      'label' => 'Birthdate',
      'category' => 'specific',
      'adminFormClass' => 'Fields_Form_Admin_Field_Birthdate',
      'helper' => 'fieldBirthdate',
    ),
    'about_me' => array(
      'base' => 'textarea',
      'label' => 'About Me',
      'category' => 'specific',
    ),
    'contract_expiry_date' => array(
      'base' => 'date',
      'label' => 'Contract Expiry Date',
      'category' => 'specific',
      'helper' => 'fieldContractExpiryDate',
    ),

    // Communications
    'website' => array(
      'base' => 'text',
      'label' => 'Website',
      'helper' => 'fieldWebsite',
      'category' => 'specific',
      'sql' => array(
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
      ),
    ),
    'twitter' => array(
      'base' => 'text',
      'label' => 'Twitter',
      'category' => 'specific',
      'helper' => 'fieldTwitter',
    ),
    'facebook' => array(
      'base' => 'text',
      'label' => 'Facebook',
      'category' => 'specific',
      'helper' => 'fieldFacebook',
    ),
    'aim' => array(
      'base' => 'text',
      'label' => 'AIM',
      'category' => 'specific',
      'helper' => 'fieldAim',
    ),

    // Location
    'city' => array(
      'base' => 'text',
      'label' => 'City',
      'category' => 'specific',
      'helper' => 'fieldText',
    ),
    'country' => array(
      'base' => 'select',
      'label' => 'Country',
      'category' => 'specific',
      'helper' => 'fieldCountry',
    ),
    'residence' => array(
      'base' => 'select',
      'label' => 'Residence',
      'category' => 'specific',
      'helper' => 'fieldCountry',
    ),
    'zip_code' => array(
      'base' => 'integer',
      'label' => 'Zip Code',
      'category' => 'specific',
      'helper' => 'fieldZipCode',
    ),
    'location' => array(
      'base' => 'text',
      'label' => 'Location',
      'category' => 'specific',
      'helper' => 'fieldLocation',
    ),

    // Dating
    'relationship_status' => array(
      'base' => 'select',
      'label' => 'Relationship Status',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'single' => 'Single',
        'relationship' => 'In a Relationship',
        'engaged' => 'Engaged',
        'married' => 'Married',
        'complicated' => 'It\'s Complicated',
        'open' => 'In an Open Relationship',
        'widow' => 'Widowed',
      )
    ),
    'looking_for' => array(
      'base' => 'multi_checkbox',
      'label' => 'Looking For',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'friendship' => 'Friendship',
        'dating' => 'Dating',
        'relationship' => 'A Relationship',
        'networking' => 'Networking',
      ),
    ),
    'partner_gender' => array(
      'base' => 'multi_checkbox',
      'label' => 'Interested In',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'men' => 'Men',
        'women' => 'Women',
      ),
    ),
    'education_level' => array(
      'base' => 'select',
      'label' => 'Education',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'high_school' => 'High School',
        'some_college' => 'Some College',
        'associates' =>  'Associates Degree',
        'bachelors' => 'Bachelors Degree',
        'graduate' => 'Graduate Degree',
        'phd' => 'PhD / Post Doctoral',
      ),
    ),
    'ethnicity' => array(
      'base' => 'multi_checkbox',
      'label' => 'Ethnicity',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'asian' => 'Asian',
        'black' => 'Black / African descent',
        'hispanic' => 'Latino / Hispanic',
        'pacific' => 'Pacific Islander',
        'white' => 'White / Caucasian',
        'other' => 'Other',
      ),
    ),
    'income' => array(
      'base' => 'select',
      'label' => 'Income',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        '25' => 'Less than $25,000',
        '25_35' => '$25,001 to $35,000',
        '35_50' => '$35,001 to $50,000',
        '50_75' => '$50,001 to $75,000',
        '75_100' => '$75,001 to $100,000',
        '100_150' => '$100,001 to $150,000',
        '150' => '$150,001+',
      ),
    ),
    'occupation' => array(
      'base' => 'select',
      'label' => 'Occupation',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
"Accountant" => "Accountant",
"Actuary" => "Actuary",
"Administration & Office Support" => "Administration & Office Support",
"Advertising, Arts, Media" => "Advertising, Arts, Media",
"Agent" => "Agent",
"Architecture & Design" => "Architecture & Design",
"Aviation Mechanic" => "Aviation Mechanic",
"Banking & Financial Services" => "Banking & Financial Services",
"Beautician" => "Beautician",
"Bricklayer" => "Bricklayer",
"Builder" => "Builder",
"Business Development " => "Business Development ",
"Business Manager" => "Business Manager",
"Call Centre & Customer Service" => "Call Centre & Customer Service",
"Carpenter" => "Carpenter",
"CEO & General Management" => "CEO & General Management",
"Clergyman" => "Clergyman",
"Club Manager" => "Club Manager",
"Coach" => "Coach",
"Community Services & Development" => "Community Services & Development",
"Construction " => "Construction ",
"Consulting & Strategy" => "Consulting & Strategy",
"Dentist" => "Dentist",
"Diesel Mechanic" => "Diesel Mechanic",
"Dietician" => "Dietician",
"Director of Sport" => "Director of Sport",
"Doctor" => "Doctor",
"Economist" => "Economist",
"Education & Training" => "Education & Training",
"Electrical/Airconditioning Technician" => "Electrical/Airconditioning Technician",
"Electrician" => "Electrician",
"Engineer" => "Engineer",
"Farming, Animals & Conservation" => "Farming, Animals & Conservation",
"Fitness Instructor" => "Fitness Instructor",
"Government & Defence" => "Government & Defence",
"Graphic Designer" => "Graphic Designer",
"Groundsperson" => "Groundsperson",
"Hairdresser" => "Hairdresser",
"Headmaster" => "Headmaster",
"Healthcare & Medical" => "Healthcare & Medical",
"Hospitality & Tourism" => "Hospitality & Tourism",
"Human Resources & Recruitment" => "Human Resources & Recruitment",
"Information & Communication Technology" => "Information & Communication Technology",
"Insurance " => "Insurance ",
"Insurance & Superannuation" => "Insurance & Superannuation",
"Interior Design" => "Interior Design",
"Labourer" => "Labourer",
"Landscaper" => "Landscaper",
"Lawyer" => "Lawyer",
"Manager" => "Manager",
"Manufacturing" => "Manufacturing",
"Marketing & Communications" => "Marketing & Communications",
"Mason" => "Mason",
"Midwife" => "Midwife",
"Mining, Resources & Energy" => "Mining, Resources & Energy",
"Nail Technician" => "Nail Technician",
"Nurse" => "Nurse",
"Nutritionist" => "Nutritionist",
"Panel Beater" => "Panel Beater",
"Pharmacist" => "Pharmacist",
"Pharmacist Assistant" => "Pharmacist Assistant",
"Physician" => "Physician",
"Physiotherapist" => "Physiotherapist",
"Pilot" => "Pilot",
"Plasterer" => "Plasterer",
"Plumber" => "Plumber",
"Professional Sportsperson" => "Professional Sportsperson",
"Project Manager" => "Project Manager",
"Psychiatrist" => "Psychiatrist",
"Psychologist" => "Psychologist",
"Radiologist" => "Radiologist",
"Real Estate & Property" => "Real Estate & Property",
"Retail & Consumer Products" => "Retail & Consumer Products",
"Sales " => "Sales ",
"Salesperson" => "Salesperson",
"Science & Technology" => "Science & Technology",
"Scientist" => "Scientist",
"Security Officer" => "Security Officer",
"Self Employed" => "Self Employed",
"Site Manager" => "Site Manager",
"Social Worker" => "Social Worker",
"Sports Administrator" => "Sports Administrator",
"Statistician" => "Statistician",
"Stockbroker" => "Stockbroker",
"Student" => "Student",
"Surgeon" => "Surgeon",
"Teacher" => "Teacher",
"Team Manager" => "Team Manager",
"Touch Football" => "Touch Football",
"Tradesman" => "Tradesman",
"Trainer" => "Trainer",
"Transport, Logistics" => "Transport, Logistics",
"Veterinarian" => "Veterinarian",
      ),
    ),
    'political_views' => array(
      'base' => 'select',
      'label' => 'Political Views',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'mid' => 'Middle of the Road',
        'far_right' => 'Very Conservative',
        'right' => 'Conservative',
        'left' => 'Liberal',
        'far_left' => 'Very Liberal',
        'anarchy' => 'Non-conformist',
        'libertarian' => 'Libertarian',
        'green' => 'Green',
        'other' => 'Other',
      ),
    ),
    'religion' => array(
      'base' => 'select',
      'label' => 'Religion',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'agnostic' => 'Agnostic',
        'atheist' => 'Atheist',
        'buddhist' => 'Buddhist',
        'taoist' => 'Taoist',
        'catholic' => 'Christian (Catholic)',
        'mormon' => 'Christian (LDS)',
        'protestant' => 'Christian (Protestant)',
        'hindu' => 'Hindu',
        'jewish' => 'Jewish',
        'muslim' => 'Muslim',
        'spiritual' => 'Spiritual',
        'other' => 'Other',
      ),
    ),
    'weight' => array(
      'base' => 'select',
      'label' => 'Weight',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'slender' => 'Slender',
        'average' => 'Average',
        'athletic' => 'Athletic',
        'heavy' => 'Heavy',
        'stocky' => 'Stocky',
        'little_fat' => 'A few extra pounds',
      ),
    ),
    'zodiac' => array(
      'base' => 'select',
      'label' => 'Zodiac',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        'capricorn' => 'Capricorn',
        'aquarius' => 'Aquarius',
        'pisces' => 'Pisces',
        'aries' => 'Aries',
        'taurus' => 'Taurus',
        'gemini' => 'Gemini',
        'cancer' => 'Cancer',
        'leo' => 'Leo',
        'virgo' => 'Virgo',
        'libra' => 'Libra',
        'scorpio' => 'Scorpio',
        'sagittarius' => 'Sagittarius',
      ),
	      ),
    'OtherSport' => array(
      'base' => 'multiselect',
      'label' => 'OtherSport',
      'helper' => 'select',
      'category' => 'specific',
      'multiOptions' => array(
"AFL" => "AFL (Aussie Rules)",
"Alpine" => "Alpine Skiing",
"Archery" => "Archery",
"Athletics" => "Athletics",
"AutoS" => "Auto Sport",
"Badminton" => "Badminton",
"Baseball" => "Baseball",
"Basketball" => "Basketball",
"Beach_Volleyball" => "Beach Volleyball",
"Biathlon" => "Biathlon",
"BMX" => "BMX",
"Bobsleigh" => "Bobsleigh",
"Body_Building" => "Body Building",
"Boxing" => "Boxing",
"Boxing" => "Boxing",
"Canoe_Slalom" => "Canoe Slalom",
"Canoe_Sprint" => "Canoe Sprint",
"Cricket" => "Cricket",
"Cross_Country_Running" => "Cross Country Running",
"Cross_Country_Skiing" => "Cross Country Skiing",
"Curling" => "Curling",
"Cycling_Road" => "Cycling Road",
"Cycling_Track" => "Cycling Track",
"Dance_Contemporary" => "Dance / Contemporary",
"Dance_Freestyle" => "Dance / Freestyle",
"Dance_Latin" => "Dance / Latin",
"Dance_Ballet" => "Dance \ Ballet",
"Darts" => "Darts",
"Diving" => "Diving",
"Equestrian_Dressage" => "Equestrian / Dressage",
"Equestrian_Eventing" => "Equestrian / Eventing",
"Equestrian_Jumping" => "Equestrian / Jumping",
"Fencing" => "Fencing",
"Figure_Skating" => "Figure Skating",
"Fitness_Health" => "Fitness Health",
"Fitness_Instructors" => "Fitness Instructors",
"Football_Soccer" => "Football (Soccer)",
"Freestyle_Skiing" => "Freestyle Skiing",
"Go_Karting" => "Go Karting",
"Golf" => "Golf",
"Gymnastics_Artistic" => "Gymnastics Artistic",
"Gymnastics_Rhythmic" => "Gymnastics Rhythmic",
"Handball" => "Handball",
"Hockey" => "Hockey",
"Ice_Hockey" => "Ice Hockey",
"Judo" => "Judo",
"Karate" => "Karate",
"Kart_Racing" => "Kart Racing",
"Kick_Boxing" => "Kick Boxing",
"Kite_Surfing" => "Kite Surfing",
"Lawn_Bowls" => "Lawn Bowls",
"Luge" => "Luge",
"Modern_Pentathlon" => "Modern Pentathlon",
"Motor_Boat_Racing" => "Motor Boat Racing",
"Motor_Cycle_Racing" => "Motor Cycle Racing",
"Mountain_Bike" => "Mountain Bike",
"Nordic_Combined" => "Nordic Combined",
"Orienteering" => "Orienteering",
"Pool" => "Pool",
"Rowing" => "Rowing",
"Rugby_League" => "Rugby League",
"Rugby_Union" => "Rugby Union",
"Running" => "Running",
"Sailing" => "Sailing",
"Shooting" => "Shooting",
"Short_Track_Speed_Skating" => "Short Track Speed Skating",
"Skeleton" => "Skeleton",
"Ski_Jumping" => "Ski Jumping",
"Snooker" => "Snooker",
"Snowboard" => "Snowboard",
"Softball" => "Softball",
"Speed_Skating" => "Speed Skating",
"Speedway_Racing" => "Speedway Racing",
"Surf_Lifesaving" => "Surf Lifesaving",
"Surfing" => "Surfing",
"Swimming" => "Swimming",
"Synchronised_Swimming" => "Synchronised Swimming",
"Table_Tennis" => "Table Tennis",
"Taekwondo" => "Taekwondo",
"Ten_Pin_Bowling" => "Ten Pin Bowling",
"Tennis" => "Tennis",
"Touch_Rugby" => "Touch Rugby",
"Trampoline" => "Trampoline",
"Triathlon" => "Triathlon",
"Volley_Ball" => "Volley Ball",
"Walking" => "Walking",
"Water_Polo" => "Water Polo",
"Weightlifting" => "Weightlifting",
"Wrestling_Freestyle" => "Wrestling Freestyle",
"Wrestling_Greco-Roman" => "Wrestling Greco-Roman",
      ),
    ),
    'PrimarySport' => array(
      'base' => 'select',
      'label' => 'PrimarySport',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
"AFL" => "AFL (Aussie Rules)",
"Alpine" => "Alpine Skiing",
"Archery" => "Archery",
"Athletics" => "Athletics",
"AutoS" => "Auto Sport",
"Badminton" => "Badminton",
"Baseball" => "Baseball",
"Basketball" => "Basketball",
"Beach_Volleyball" => "Beach Volleyball",
"Biathlon" => "Biathlon",
"BMX" => "BMX",
"Bobsleigh" => "Bobsleigh",
"Body_Building" => "Body Building",
"Boxing" => "Boxing",
"Boxing" => "Boxing",
"Canoe_Slalom" => "Canoe Slalom",
"Canoe_Sprint" => "Canoe Sprint",
"Cricket" => "Cricket",
"Cross_Country_Running" => "Cross Country Running",
"Cross_Country_Skiing" => "Cross Country Skiing",
"Curling" => "Curling",
"Cycling_Road" => "Cycling Road",
"Cycling_Track" => "Cycling Track",
"Dance_Contemporary" => "Dance / Contemporary",
"Dance_Freestyle" => "Dance / Freestyle",
"Dance_Latin" => "Dance / Latin",
"Dance_Ballet" => "Dance \ Ballet",
"Darts" => "Darts",
"Diving" => "Diving",
"Equestrian_Dressage" => "Equestrian / Dressage",
"Equestrian_Eventing" => "Equestrian / Eventing",
"Equestrian_Jumping" => "Equestrian / Jumping",
"Fencing" => "Fencing",
"Figure_Skating" => "Figure Skating",
"Fitness_Health" => "Fitness Health",
"Fitness_Instructors" => "Fitness Instructors",
"Football_Soccer" => "Football (Soccer)",
"Freestyle_Skiing" => "Freestyle Skiing",
"Go_Karting" => "Go Karting",
"Golf" => "Golf",
"Gymnastics_Artistic" => "Gymnastics Artistic",
"Gymnastics_Rhythmic" => "Gymnastics Rhythmic",
"Handball" => "Handball",
"Hockey" => "Hockey",
"Ice_Hockey" => "Ice Hockey",
"Judo" => "Judo",
"Karate" => "Karate",
"Kart_Racing" => "Kart Racing",
"Kick_Boxing" => "Kick Boxing",
"Kite_Surfing" => "Kite Surfing",
"Lawn_Bowls" => "Lawn Bowls",
"Luge" => "Luge",
"Modern_Pentathlon" => "Modern Pentathlon",
"Motor_Boat_Racing" => "Motor Boat Racing",
"Motor_Cycle_Racing" => "Motor Cycle Racing",
"Mountain_Bike" => "Mountain Bike",
"Netball" => "Netball",
"Nordic_Combined" => "Nordic Combined",
"Orienteering" => "Orienteering",
"Pool" => "Pool",
"Rowing" => "Rowing",
"Rugby_League" => "Rugby League",
"Rugby_Union" => "Rugby Union",
"Running" => "Running",
"Sailing" => "Sailing",
"Shooting" => "Shooting",
"Short_Track_Speed_Skating" => "Short Track Speed Skating",
"Skeleton" => "Skeleton",
"Ski_Jumping" => "Ski Jumping",
"Snooker" => "Snooker",
"Snowboard" => "Snowboard",
"Softball" => "Softball",
"Speed_Skating" => "Speed Skating",
"Speedway_Racing" => "Speedway Racing",
"Stand Up Paddle Boarding" => "Stand Up Paddle Boarding",
"Surf_Lifesaving" => "Surf Lifesaving",
"Surfing" => "Surfing",
"Swimming" => "Swimming",
"Synchronised_Swimming" => "Synchronised Swimming",
"Table_Tennis" => "Table Tennis",
"Taekwondo" => "Taekwondo",
"Ten_Pin_Bowling" => "Ten Pin Bowling",
"Tennis" => "Tennis",
"Touch_Rugby" => "Touch Rugby",
"Trampoline" => "Trampoline",
"Triathlon" => "Triathlon",
"Volley_Ball" => "Volley Ball",
"Walking" => "Walking",
"Water_Polo" => "Water Polo",
"Weightlifting" => "Weightlifting",
"Wrestling_Freestyle" => "Wrestling Freestyle",
"Wrestling_Greco-Roman" => "Wrestling Greco-Roman",
      ),
    ),

    'interests' => array(
      'base' => 'textarea',
      'label' => 'Interests',
      'category' => 'specific',
      'helper' => 'fieldTextareaLinked',
    ),

    'currency' => array(
      'base' => 'float',
      'label' => 'Currency',
      'category' => 'specific',
      'helper' => 'fieldCurrency',
      'adminFormClass' => 'Fields_Form_Admin_Field_Currency',
    ),
	    ),
    'primary_sport' => array(
      'base' => 'select',
      'label' => 'Primary Sport',
      'helper' => 'fieldOptions',
      'category' => 'specific',
      'multiOptions' => array(
        "AFL" => "AFL (Aussie Rules)",
"Alpine" => "Alpine Skiing",
"Archery" => "Archery",

      )
  ),
) ?>