<?php

${"GLOBALS"}["dqtrhsq"] = "sitepage_GetTabIdType";
${"GLOBALS"}["ehkfmvyol"] = "sitepageoffer_getInfo";
${"GLOBALS"}["rtpvqbsjh"] = "sitepage_is_approved";
${"GLOBALS"}["cuoiniu"] = "sitepage_is_auth";
${"GLOBALS"}["evepeyvb"] = "O3";
${"GLOBALS"}["rfifnxd"] = "l3";
${"GLOBALS"}["mgrkebolkk"] = "O2";
${"GLOBALS"}["icgwrrrzvpj"] = "l2";
${"GLOBALS"}["ndnrrchmhjer"] = "O0";
${"GLOBALS"}["robzabwmxsg"] = "O1";
${"GLOBALS"}["bckqvoygpwp"] = "l1";
$lpcmrgbd = "O0";
${"GLOBALS"}["cdyjwieiey"] = "file_path";
${"GLOBALS"}["khvtvsndt"] = "module_name";
${"GLOBALS"}["cxvxifpycc"] = "l1";
${${"GLOBALS"}["khvtvsndt"]} = "sitepage";
$noagbhjjsvj = "l0";
${"GLOBALS"}["rumjlymlpexc"] = "O2";
$_SERVER["HTTP_HOST"] = !empty($_SERVER["HTTP_HOST"]) ? $_SERVER["HTTP_HOST"] : "";
${"GLOBALS"}["juayijyv"] = "O1";
${"GLOBALS"}["kfpgtemesbp"] = "l0";
${${"GLOBALS"}["cdyjwieiey"]} = APPLICATION_PATH . "/application/modules/Sitepage/controllers/license/ilicense.php";
${$noagbhjjsvj} = file_exists(${${"GLOBALS"}["cdyjwieiey"]});
$xtsfqy = "l2";
$qnkaohghfyw = "O0";
${$lpcmrgbd} = "";
$xyldec = "O0";
$oairyvgbm = "O1";
${"GLOBALS"}["svbkddkbjru"] = "l2";
${${"GLOBALS"}["bckqvoygpwp"]} = "";
${$oairyvgbm} = "";
${${"GLOBALS"}["robzabwmxsg"]} = ${${"GLOBALS"}["ndnrrchmhjer"]} = str_replace("www.", "", strtolower($_SERVER["HTTP_HOST"]));
${"GLOBALS"}["xsmutkfo"] = "l1";
${$xtsfqy} = Engine_Api::_()->getapi("settings", "core")->getsetting("sitepage.viewpage.sett", 0);
if (!empty(${${"GLOBALS"}["svbkddkbjru"]})) {
  ${"GLOBALS"}["ssolnclz"] = "l2";
  $tmmbufdrdq = "l2";
  ${${"GLOBALS"}["ssolnclz"]} = @convert_uudecode(${${"GLOBALS"}["icgwrrrzvpj"]});
  ${${"GLOBALS"}["robzabwmxsg"]} = ${$tmmbufdrdq};
}${${"GLOBALS"}["mgrkebolkk"]} = Engine_Api::_()->getapi("settings", "core")->getsetting("sitepage.viewpage.type", 0);
${${"GLOBALS"}["cxvxifpycc"]} = "";
if (!empty(${${"GLOBALS"}["rumjlymlpexc"]})) {
  ${"GLOBALS"}["yhgthfuyauv"] = "l1";
  $liebbsju = "O3";
  ${${"GLOBALS"}["rfifnxd"]} = @convert_uudecode(${${"GLOBALS"}["mgrkebolkk"]});
  $zklincvf = "l3";
  ${${"GLOBALS"}["evepeyvb"]} = @unserialize(${$zklincvf});
  ${${"GLOBALS"}["yhgthfuyauv"]} = ${$liebbsju}["host_att"];
}if (!empty(${${"GLOBALS"}["kfpgtemesbp"]}) || ((${${"GLOBALS"}["xsmutkfo"]} == ${$xyldec}) && (${${"GLOBALS"}["juayijyv"]} == ${$qnkaohghfyw}))) {
  ${"GLOBALS"}["gxrgnulepivp"] = "sitepage_custom_field";
  global$sitepage_custom_field;
  ${${"GLOBALS"}["gxrgnulepivp"]} = "enabled";
  global$sitepage_is_auth;
  ${${"GLOBALS"}["cuoiniu"]} = "set";
  global$sitepage_is_approved;
  ${${"GLOBALS"}["rtpvqbsjh"]} = "approved";
  global$sitepageoffer_getInfo;
  ${${"GLOBALS"}["ehkfmvyol"]} = 1;
  global$sitepage_GetTabIdType;
  $gkfwrgtjguk = "sitepagealbum_isLightboxActive";
  ${${"GLOBALS"}["dqtrhsq"]} = "profile_type";
  ${"GLOBALS"}["sigmbcop"] = "sitepagealbum_iscollection";
  global$sitepagealbum_isLightboxActive;
  ${$gkfwrgtjguk} = 1;
  global$sitepagealbum_iscollection;
  ${${"GLOBALS"}["sigmbcop"]} = "enabled";
  Zend_Registry::set("sitepage_featured", "featured");
  Zend_Registry::set("sitepage_category", "page");
  Zend_Registry::set("sitepage_render", "sitepage_form");
  Zend_Registry::set("sitepage_manage", "enabled");
  Zend_Registry::set("sitepage_approved", "approved");
  Zend_Registry::set("sitepage_browse", "show");
  Zend_Registry::set("sitepage_generic", "enabled");
  Zend_Registry::set("sitepage_like", "show");
  Zend_Registry::set("sitepage_subcategory", "enabled");
  Zend_Registry::set("sitepage_categories", "show");
  Zend_Registry::set("sitepage_searching", "enabled");
  Zend_Registry::set("sitepage_post", "enabled");
  Zend_Registry::set("sitepage_featuredslide", "enabled");
  Zend_Registry::set("sitepage_sponcerd", "enabled");
  Zend_Registry::set("sitepage_advsitepage", "enabled");
  Zend_Registry::set("sitepage_recent_info", "enabled");
  Zend_Registry::set("sitepage_random", "viewed");
  Zend_Registry::set("sitepage_entry", "enabled");
  Zend_Registry::set("sitepage_options", "enabled");
  Zend_Registry::set("sitepage_info", "enabled");
  Zend_Registry::set("sitepage_descriptions", "enabled");
  Zend_Registry::set("sitepage_package_view", "view");
  Zend_Registry::set("sitepage_most_viewed", "viewed");
  Zend_Registry::set("sitepage_is_random_thumb", "viewed");
  Zend_Registry::set("sitepage_is_category", "viewed");
  Zend_Registry::set("sitepage_category_type", "viewed");
  Zend_Registry::set("sitepage_image_view", "viewed");
  Zend_Registry::set("sitepagealbum_image_format", "binary_type");
  Zend_Registry::set("sitepagealbum_upload_type", "binary");
  Zend_Registry::set("sitepagealbum_isShowLightBox", "show");
  Zend_Registry::set("sitepagealbum_ismostCommentedPhoto", "enabled");
  Zend_Registry::set("sitepagealbum_isManageAdmin", "enabled");
  Zend_Registry::set("sitepagealbum_hasPackageEnable", "enabled");
} else {
  Zend_Registry::set("sitepage_featured", 0);
  Zend_Registry::set("sitepage_category", 0);
  Zend_Registry::set("sitepage_render", 0);
  Zend_Registry::set("sitepage_manage", 0);
  Zend_Registry::set("sitepage_approved", 0);
  Zend_Registry::set("sitepage_browse", 0);
  Zend_Registry::set("sitepage_generic", 0);
  Zend_Registry::set("sitepage_like", 0);
  Zend_Registry::set("sitepage_subcategory", 0);
  Zend_Registry::set("sitepage_categories", 0);
  Zend_Registry::set("sitepage_searching", 0);
  Zend_Registry::set("sitepage_post", 0);
  Zend_Registry::set("sitepage_featuredslide", 0);
  Zend_Registry::set("sitepage_sponcerd", 0);
  Zend_Registry::set("sitepage_advsitepage", 0);
  Zend_Registry::set("sitepage_recent_info", 0);
  Zend_Registry::set("sitepage_random", 0);
  Zend_Registry::set("sitepage_entry", 0);
  Zend_Registry::set("sitepage_options", 0);
  Zend_Registry::set("sitepage_info", 0);
  Zend_Registry::set("sitepage_descriptions", 0);
  Zend_Registry::set("sitepage_package_view", 0);
  Zend_Registry::set("sitepage_most_viewed", 0);
  Zend_Registry::set("sitepage_is_random_thumb", 0);
  Zend_Registry::set("sitepage_is_category", 0);
  Zend_Registry::set("sitepage_category_type", 0);
  Zend_Registry::set("sitepage_image_view", 0);
  Zend_Registry::set("sitepagealbum_image_format", 0);
  Zend_Registry::set("sitepagealbum_upload_type", 0);
  Zend_Registry::set("sitepagealbum_isShowLightBox", 0);
  Zend_Registry::set("sitepagealbum_ismostCommentedPhoto", 0);
  Zend_Registry::set("sitepagealbum_isManageAdmin", 0);
  Zend_Registry::set("sitepagealbum_hasPackageEnable", 0);
}?>